import type { Metadata } from "next";
import Link from "next/link";
import { FileText, FolderOpen } from "lucide-react";

import OrgHeader from "@/components/organizations/OrgHeader";
import { getUserOrganizations, requireOrganizationMembership } from "@/lib/organizations/server";
import { createClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Reports" };

type ReportRow = {
  id: string;
  title: string;
  summary: string | null;
  confidence: number | null;
  created_at: string;
};

function fmt(iso: string): string {
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? "" : new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(d);
}

export default async function ReportsPage({
  params,
}: {
  params: Promise<{ organizationId: string }>;
}) {
  const { organizationId } = await params;
  const { organization } = await requireOrganizationMembership(organizationId);
  const [allMemberships, supabase] = await Promise.all([getUserOrganizations(), createClient()]);

  const { data } = await supabase
    .from("reports")
    .select("id, title, summary, confidence, created_at")
    .eq("organization_id", organization.id)
    .order("created_at", { ascending: false });

  const reports = (data ?? []) as ReportRow[];

  return (
    <div className="min-h-screen bg-zinc-50 dark:bg-zinc-950">
      <OrgHeader
        organizations={allMemberships.map((m) => ({ organization: m.organization, role: m.membership.role }))}
        currentOrganizationId={organization.id}
      />
      <main className="mx-auto max-w-4xl space-y-8 px-6 py-10">
        <div>
          <p className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-widest text-indigo-500">
            <FileText className="h-3.5 w-3.5" aria-hidden="true" /> {organization.name}
          </p>
          <h1 className="mt-2 text-3xl font-semibold tracking-tight text-zinc-900 dark:text-white">Reports</h1>
          <p className="mt-1.5 text-sm text-zinc-500 dark:text-zinc-400">
            Cited research reports generated by the agent, scoped to this organization.
          </p>
        </div>

        {reports.length === 0 ? (
          <div className="rounded-2xl border-2 border-dashed border-zinc-300 bg-white/60 px-6 py-14 text-center dark:border-zinc-700 dark:bg-zinc-900/40">
            <FolderOpen className="mx-auto h-8 w-8 text-zinc-300 dark:text-zinc-600" />
            <p className="mt-3 text-sm text-zinc-500 dark:text-zinc-400">
              No reports yet. Run a research question to generate one.
            </p>
            <Link href={`/organizations/${organization.id}/research`} className="btn-primary mt-5">
              Start research
            </Link>
          </div>
        ) : (
          <ul className="divide-y divide-zinc-100 overflow-hidden rounded-2xl border border-zinc-200 bg-white dark:divide-zinc-800 dark:border-zinc-800 dark:bg-zinc-900">
            {reports.map((report) => (
              <li key={report.id}>
                <Link
                  href={`/organizations/${organization.id}/reports/${report.id}`}
                  className="flex items-start justify-between gap-3 px-5 py-4 transition hover:bg-zinc-50 dark:hover:bg-zinc-800/60"
                >
                  <div className="min-w-0">
                    <p className="truncate text-sm font-semibold text-zinc-900 dark:text-white">{report.title}</p>
                    <p className="mt-1 line-clamp-2 text-xs text-zinc-500 dark:text-zinc-400">{report.summary}</p>
                  </div>
                  <div className="shrink-0 text-right text-xs text-zinc-400">
                    <p>{fmt(report.created_at)}</p>
                    {report.confidence != null && <p className="mt-1 text-emerald-600 dark:text-emerald-400">{Math.round(report.confidence * 100)}% confidence</p>}
                  </div>
                </Link>
              </li>
            ))}
          </ul>
        )}
      </main>
    </div>
  );
}
